document.getElementById('donation-btn').addEventListener('click',function(){
    window.location.href="index.html";
})
document.getElementById('history-btn').addEventListener('click',function(){
    window.location.href="history.html";
})
document.getElementById('blog-btn').addEventListener('click',function(){
    window.location.href="blog.html";
})